---
- name: Create root object "{{ ldap_base_dc }}"
  community.general.ldap_entry:
    state: present
    dn: '{{ ldap_base_dc }}'
    objectClass:
      - dcObject
      - organization
      - top
    attributes:
      o: ldap

- name: Create basic organizational units
  community.general.ldap_entry:
    state: present
    dn: '{{ item.dn }}'
    attributes:
      ou: '{{ item.ou }}'
    objectClass:
      - organizationalUnit
  with_items:
    - dn: '{{ ldap_dn_admin_group }}'
      ou: admin
    - dn: '{{ ldap_dn_services_group }}'
      ou: services

- name: Create super admin group
  community.general.ldap_entry:
    state: present
    dn: '{{ ldap_dn_admin_group }}'
    objectClass:
      - organizationalUnit
      - top
    attributes:
      ou: '{{ ldap_admin_group }}'

- name: Configure admin user
  community.general.ldap_attrs:
    state: exact
    dn: olcDatabase={1}mdb,cn=config
    attributes:
      olcRootDN: '{{ ldap_dn_bind }}'
      olcRootPW: '{{ ldap_dn_bind_pass }}'
