---
- name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
  community.crypto.openssl_privatekey:
    path: '{{ ldap_tls_dir }}/ldaps.key'
    owner: openldap
    group: openldap

- name: Generate an OpenSSL Certificate Signing Request
  community.crypto.openssl_csr:
    path: '{{ ldap_tls_dir }}/ldaps.csr'
    privatekey_path: '{{ ldap_tls_dir }}/ldaps.key'
    country_name: JP
    common_name: magi.ssc-otemachi.ocn.ad.jp
    owner: openldap
    group: openldap

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: '{{ ldap_tls_dir }}/ldaps.crt'
    privatekey_path: '{{ ldap_tls_dir }}/ldaps.key'
    csr_path: '{{ ldap_tls_dir }}/ldaps.csr'
    provider: selfsigned
    owner: openldap
    group: openldap

- name: Configure OpenLDAP server TLS/SSL
  ldap_attrs:
    dn: 'cn=config'
    attributes:
      olcTLSCACertificateFile: '{{ ldap_tls_cacert }}'
      olcTLSCertificateFile: '{{ ldap_tls_dir }}/ldaps.crt'
      olcTLSCertificateKeyFile: '{{ ldap_tls_dir }}/ldaps.key'
    state: exact
  notify: restart slapd
