---
- name: Configure ldap.conf
  ansible.builtin.template:
    src: ldap.conf
    dest: /etc/ldap/ldap.conf

- name: Configure base DN
  community.general.ldap_attrs:
    state: exact
    dn: olcDatabase={1}mdb,cn=config
    attributes:
      olcSuffix: '{{ ldap_base_dc }}'

- name: Configure LDAP modules
  community.general.ldap_entry:
    state: present
    dn: cn=module{1},cn=config
    objectClass: olcModuleList
    attributes:
      olcModulePath: /usr/lib/ldap
      olcModuleLoad:
        - memberof
        - refint

- name: Configure LDAP memberof overlay
  community.general.ldap_entry:
    state: present
    dn: olcOverlay={0}memberof,olcDatabase={1}mdb,cn=config
    objectClass:
      - olcConfig
      - olcMemberOf
      - olcOverlayConfig
      - top
    attributes:
      olcOverlay: memberof
      olcMemberOfDangling: ignore
      olcMemberOfRefInt: 'TRUE'
      olcMemberOfGroupOC: groupOfNames
      olcMemberOfMemberAD: member
      olcMemberOfMemberOfAD: memberOf

- name: Configure LDAP refint overlay
  community.general.ldap_entry:
    state: present
    dn: olcOverlay={1}refint,olcDatabase={1}mdb,cn=config
    objectClass:
      - olcConfig
      - olcRefintConfig
      - olcOverlayConfig
      - top
    attributes:
      olcOverlay: 'refint'
      olcRefintAttribute: memberof member manager owner

- name: Configure permissions
  notify: restart slapd
  community.general.ldap_attrs:
    state: exact
    dn: olcDatabase={1}mdb,cn=config
    attributes:
      olcAccess:
        - >-
          {0}to dn.subtree="{{ ldap_base_dc }}"
          by dn.exact="{{ ldap_dn_external }}" manage
          by dn.exact="{{ ldap_dn_bind }}" manage
          by dn.children="{{ ldap_dn_admin_group }}" manage
          by dn.children="{{ ldap_dn_services_group }}" write
          by self write
          by anonymous auth
          by * none
        - >-
          {1}to attrs=userPassword
          by self write
          by anonymous auth
          by * none
