---
- name: Install LDAP dependencies
  ansible.builtin.apt:
    name: '{{ ldap_packages }}'
    state: present

- name: Enable ldaps:/// as slapd service
  ansible.builtin.lineinfile:
    path: /etc/default/slapd
    state: present
    regexp: 'SLAPD_SERVICES="ldap:/// ldapi:///"'
    line: 'SLAPD_SERVICES="ldap:/// ldapi:/// ldaps:///"'

- name: Start slapd
  ansible.builtin.systemd:
    name: slapd
    state: started
    enabled: true
    masked: false
