---
- name: Create organization {{ ldap_organization }}
  ldap_entry:
    state: present
    dn: 'dc={{ ldap_organization }},{{ ldap_base_dc }}'
    objectClass:
      - organization
      - dcObject
      - top
    attributes:
      o: '{{ ldap_organization }}'

- name: Create organizational units for {{ ldap_organization }}
  ldap_entry:
    state: present
    dn: '{{ item.dn }}'
    attributes:
      ou: '{{ item.ou }}'
    objectClass:
      - organizationalUnit
  with_items:
    - dn: 'ou=users,dc={{ ldap_organization }},{{ ldap_base_dc }}'
      ou: users
    - dn: 'ou=groups,dc={{ ldap_organization }},{{ ldap_base_dc }}'
      ou: groups
