---
- name: packages | upgrade
  ansible.builtin.apt:
    upgrade: full
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true

- name: packages | install
  ansible.builtin.apt:
    name: "{{ packages }}"
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true

- name: packages | add docker gpg key
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    dest: "/usr/share/keyrings/docker.asc"

- name: packages | add docker apt source
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker.asc] https://download.docker.com/linux/ubuntu jammy stable"
    state: present

- name: packages | install docker
  ansible.builtin.apt:
    name: "docker-ce"
    update_cache: yes
    state: present

