---
- name: sshd | service start
  ansible.builtin.systemd:
    name: sshd
    enabled: yes
    state: started

- name: sshd | configure sshd_config
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    backup: yes
    validate: sshd -t -f %s
    regexp: '{{ item.pattern }}'
    line: '{{ item.replace }}'
  loop:
    - pattern: '^#?\s*PermitRootLogin'
      replace: 'PermitRootLogin no'
    - pattern: '^#PermitEmptyPasswords'
      replace: 'PermitEmptyPasswords no'
  notify: sshd | restart service
