---
- name: Copy SSSD configuration file
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    mode: 0600
    backup: true
    owner: root
    group: root
  notify: restart sssd

- name: Query SSSD in nsswitch.conf
  replace:
    dest: /etc/nsswitch.conf
    regexp: '^({{ item }}(?!.*\bsss\b).*)$'
    replace: '\1 sss'
    backup: true
  with_items:
    - passwd
    - shadow
    - group
    - services
    - netgroup
    - automount

- name: Don't query SSSD for sudoers in nsswitch.conf
  replace:
    dest: /etc/nsswitch.conf
    regexp: '^(sudoers.*)(\bsss)(\b.*)$'
    replace: '\1 \3'
    backup: true

- name: Ensure home directories are created upon login
  lineinfile:
    dest: /etc/pam.d/common-account
    regexp: 'pam_mkhomedir\.so'
    line: 'session required pam_mkhomedir.so skel=/etc/skel/ umask=0022'
    state: present

- name: Start and enable auth services
  service:
    name: sssd
    state: started
    enabled: true

- name: Add LDAP users to sudoers
  template:
    src: ldap_sudo_users.j2
    dest: '/etc/sudoers.d/ldap_sudo_users'
    validate: 'visudo -cf %s'

- name: Add LDAP groups to sudoers
  template:
    src: ldap_sudo_groups.j2
    dest: '/etc/sudoers.d/ldap_sudo_groups'
    validate: 'visudo -cf %s'

- name: Add pam_mkhomedir for Debian machines
  copy:
    src: pam_mkhomedir
    dest: /usr/share/pam-configs/mkhomedir
  notify:
    - run pam auth update
