---
- name: sssd | restart service
  ansible.builtin.systemd:
    name: sssd
    state: restarted

- name: sshd | restart service
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: pam | auth update
  ansible.builtin.shell: pam-auth-update --package
