---
- name: start slapd
  service:
    name: slapd
    state: started

- name: restart slapd
  service:
    name: slapd
    state: restarted

- name: restart sssd
  service:
    name: sssd
    state: restarted

- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: run pam auth update
  shell: pam-auth-update --package
