---
- name: start slapd
  ansible.builtin.systemd:
    name: slapd
    state: started

- name: restart slapd
  ansible.builtin.systemd:
    name: slapd
    state: restarted

- name: restart sssd
  ansible.builtin.systemd:
    name: sssd
    state: restarted

- name: restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: run pam auth update
  ansible.builtin.shell: pam-auth-update --package
