---
- name: packages | install
  ansible.builtin.apt:
    name: "{{ packages }}"
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
