---
packages:
  - sudo
  - openssh-server
  - ldap-utils
  - sssd
  - sssd-ldap
  - libnss-sss

ldap_organisation: "Example Org."
ldap_domain:  "example.com"
ldap_base_dn: "dc=example,dc=com"
ldap_bind_dn: "cn=admin,{{ ldap_base_dn }}"
ldap_admin_password: "admin"
ldap_user_search_filter:
ldap_group_search_filter:
ldap_user_search_base:
ldap_group_search_base:
ldap_access_filter_groups: []
ldap_access_unix_groups: []
ldap_access_filter_users: []
